### ISSUE TITLE
missing function

### ISSUE THREAD

**Issue by whyyshiny** [Dr4iv3rNope/E2Power#1]
https://github.com/HyvelEurope/E2Power/blob/0ff03fe5066857d69e04343206de90313847067e/lua/entities/gmod_wire_expression2/core/custom/health.lua#L58

**Comment by Dr4iv3rNope** [comment]
Function is already defined in wiremod: https://github.com/wiremod/wire/blob/f5c907cfde0e66452f4e09299efcacff2549e51b/lua/entities/gmod_wire_expression2/core/entity.lua#L260-L263
